/**
 * The emoji the picker offers, as `[glyph, search words]`.
 *
 * Curated rather than the full Unicode set: the complete list is ~1,900
 * glyphs, most of which nobody has ever sent, and shipping it (with the names
 * needed to make search work) would be tens of kilobytes of JS parsed on
 * every cold start for a sheet that opens occasionally. This is the part of it
 * people actually use, grouped the way every keyboard groups it, and search
 * covers the names rather than only the exact word.
 *
 * Skin tones are left off deliberately: a tone modifier turns one chip into
 * six, and a reaction bar is not the place to make that choice. The neutral
 * form is what gets stored, so nothing here can go stale against the database
 * — `chat_reactions.emoji` is free text.
 */

export interface EmojiGroup {
  id: string;
  label: string;
  /** Shown as the group's tab. */
  icon: string;
  emoji: [glyph: string, words: string][];
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    id: 'smileys',
    label: 'Smileys',
    icon: '😀',
    emoji: [
      ['😀', 'grin smile happy'],
      ['😃', 'smile happy joy'],
      ['😄', 'smile laugh happy'],
      ['😁', 'beam grin happy'],
      ['😆', 'laugh squint haha'],
      ['😅', 'sweat laugh relief'],
      ['🤣', 'rofl rolling laughing haha'],
      ['😂', 'joy tears laughing haha'],
      ['🙂', 'slight smile'],
      ['🙃', 'upside down silly'],
      ['😉', 'wink'],
      ['😊', 'blush smile pleased'],
      ['😇', 'halo angel innocent'],
      ['🥰', 'love hearts adore'],
      ['😍', 'heart eyes love'],
      ['😘', 'kiss blow'],
      ['😗', 'kiss'],
      ['😚', 'kiss closed eyes'],
      ['😋', 'yum tasty tongue'],
      ['😛', 'tongue cheeky'],
      ['😜', 'wink tongue joke'],
      ['🤪', 'zany crazy silly'],
      ['🤨', 'raised eyebrow sceptical'],
      ['🧐', 'monocle inspect examine'],
      ['🤓', 'nerd glasses geek'],
      ['😎', 'cool sunglasses'],
      ['🥳', 'party celebrate'],
      ['😏', 'smirk sly'],
      ['😒', 'unamused meh'],
      ['😞', 'disappointed sad'],
      ['😔', 'pensive sad'],
      ['😟', 'worried'],
      ['😕', 'confused'],
      ['🙁', 'frown slight'],
      ['😣', 'persevere struggle'],
      ['😖', 'confounded'],
      ['😫', 'tired exhausted'],
      ['😩', 'weary'],
      ['🥺', 'pleading please'],
      ['😢', 'cry sad tear'],
      ['😭', 'sob crying loud'],
      ['😤', 'triumph steam determined'],
      ['😠', 'angry'],
      ['😡', 'rage furious'],
      ['🤬', 'swearing cursing'],
      ['🤯', 'mind blown exploding'],
      ['😳', 'flushed embarrassed'],
      ['🥵', 'hot heat sweating'],
      ['🥶', 'cold freezing'],
      ['😱', 'scream shocked fear'],
      ['😨', 'fearful scared'],
      ['😰', 'anxious sweat'],
      ['😥', 'sad relieved'],
      ['😓', 'downcast sweat'],
      ['🤗', 'hug hugging'],
      ['🤔', 'thinking hmm'],
      ['🤭', 'oops giggle'],
      ['🤫', 'shush quiet'],
      ['🤥', 'lying pinocchio'],
      ['😶', 'no mouth speechless'],
      ['😐', 'neutral'],
      ['😑', 'expressionless'],
      ['😬', 'grimace awkward'],
      ['🙄', 'eye roll'],
      ['😯', 'hushed surprised'],
      ['😴', 'sleeping zzz'],
      ['🤤', 'drooling'],
      ['😪', 'sleepy'],
      ['😵', 'dizzy'],
      ['🤐', 'zipper mouth'],
      ['🥴', 'woozy'],
      ['🤢', 'nauseated sick'],
      ['🤮', 'vomiting sick'],
      ['🤧', 'sneeze'],
      ['😷', 'mask sick'],
      ['🤒', 'thermometer ill'],
      ['🤕', 'bandage hurt'],
      ['🤑', 'money mouth rich'],
      ['🤠', 'cowboy'],
      ['😈', 'devil mischief'],
      ['💀', 'skull dead'],
      ['👻', 'ghost'],
      ['👽', 'alien'],
      ['🤖', 'robot bot'],
      ['💩', 'poop'],
      ['🎃', 'pumpkin halloween'],
    ],
  },
  {
    id: 'gestures',
    label: 'Gestures',
    icon: '👍',
    emoji: [
      ['👍', 'thumbs up yes agree good ok'],
      ['👎', 'thumbs down no bad disagree'],
      ['👌', 'ok perfect'],
      ['🤌', 'pinched fingers'],
      ['✌️', 'peace victory'],
      ['🤞', 'fingers crossed luck'],
      ['🤟', 'love you'],
      ['🤘', 'rock horns'],
      ['🤙', 'call me shaka'],
      ['👈', 'point left'],
      ['👉', 'point right'],
      ['👆', 'point up'],
      ['👇', 'point down'],
      ['☝️', 'index up one'],
      ['✋', 'raised hand stop'],
      ['🤚', 'back of hand'],
      ['🖐️', 'hand fingers splayed'],
      ['🖖', 'vulcan spock'],
      ['👋', 'wave hello bye'],
      ['🤝', 'handshake deal agree'],
      ['🙏', 'pray thanks please'],
      ['✍️', 'writing hand sign'],
      ['💪', 'muscle strong'],
      ['🦾', 'mechanical arm'],
      ['👏', 'clap applause well done'],
      ['🙌', 'raised hands celebrate'],
      ['👐', 'open hands'],
      ['🤲', 'palms up'],
      ['🤜', 'fist right'],
      ['🤛', 'fist left'],
      ['✊', 'raised fist'],
      ['👊', 'fist bump punch'],
      ['🫶', 'heart hands love'],
      ['🖕', 'middle finger'],
      ['💅', 'nail polish'],
      ['🤳', 'selfie'],
      ['🧠', 'brain smart'],
      ['👀', 'eyes look watching'],
      ['👁️', 'eye'],
      ['👄', 'mouth lips'],
      ['👂', 'ear listen'],
      ['👃', 'nose'],
    ],
  },
  {
    id: 'people',
    label: 'People',
    icon: '🧑',
    emoji: [
      ['👶', 'baby'],
      ['🧒', 'child'],
      ['🧑', 'person adult'],
      ['👨', 'man'],
      ['👩', 'woman'],
      ['🧓', 'older person'],
      ['🧑‍💼', 'office worker staff'],
      ['🧑‍🏭', 'factory worker production'],
      ['🧑‍🔧', 'mechanic maintenance'],
      ['🧑‍🍳', 'cook chef'],
      ['🧑‍🌾', 'farmer'],
      ['🧑‍⚕️', 'health worker doctor nurse'],
      ['🧑‍🏫', 'teacher'],
      ['🧑‍💻', 'developer technologist coder'],
      ['🧑‍🎨', 'artist designer'],
      ['👮', 'police officer'],
      ['🕵️', 'detective investigate'],
      ['💂', 'guard'],
      ['👷', 'construction worker safety'],
      ['🤴', 'prince'],
      ['👸', 'princess'],
      ['🦸', 'superhero'],
      ['🧙', 'mage wizard'],
      ['🙋', 'raising hand volunteer'],
      ['🙆', 'ok gesture person'],
      ['🙅', 'no gesture person'],
      ['💁', 'tipping hand information'],
      ['🤦', 'facepalm'],
      ['🤷', 'shrug dunno'],
      ['🧘', 'lotus calm meditation'],
      ['🏃', 'running'],
      ['🚶', 'walking'],
      ['💃', 'dancing woman'],
      ['🕺', 'dancing man'],
      ['👥', 'people group team'],
      ['🗣️', 'speaking head talk'],
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    icon: '🌿',
    emoji: [
      ['🐶', 'dog puppy'],
      ['🐱', 'cat kitten'],
      ['🐭', 'mouse'],
      ['🐰', 'rabbit bunny'],
      ['🦊', 'fox'],
      ['🐻', 'bear'],
      ['🐼', 'panda'],
      ['🐨', 'koala'],
      ['🐯', 'tiger'],
      ['🦁', 'lion'],
      ['🐮', 'cow'],
      ['🐷', 'pig'],
      ['🐸', 'frog'],
      ['🐵', 'monkey'],
      ['🐔', 'chicken'],
      ['🐦', 'bird'],
      ['🦅', 'eagle'],
      ['🦉', 'owl'],
      ['🐝', 'bee'],
      ['🦋', 'butterfly'],
      ['🐌', 'snail slow'],
      ['🐜', 'ant'],
      ['🕷️', 'spider'],
      ['🐢', 'turtle'],
      ['🐍', 'snake'],
      ['🐙', 'octopus'],
      ['🐠', 'fish tropical'],
      ['🐬', 'dolphin'],
      ['🐳', 'whale'],
      ['🐘', 'elephant'],
      ['🐄', 'cow buffalo'],
      ['🐐', 'goat'],
      ['🌵', 'cactus'],
      ['🌲', 'tree evergreen'],
      ['🌳', 'tree'],
      ['🌴', 'palm tree'],
      ['🌱', 'seedling grow'],
      ['🌿', 'herb leaf'],
      ['☘️', 'shamrock clover'],
      ['🍀', 'four leaf clover luck'],
      ['🌾', 'sheaf rice grain'],
      ['🌷', 'tulip'],
      ['🌹', 'rose'],
      ['🌸', 'blossom cherry'],
      ['🌻', 'sunflower'],
      ['🌼', 'daisy flower'],
      ['🌞', 'sun face'],
      ['🌝', 'full moon face'],
      ['⭐', 'star'],
      ['🌟', 'glowing star sparkle'],
      ['✨', 'sparkles magic new'],
      ['⚡', 'lightning power fast'],
      ['🔥', 'fire hot lit'],
      ['💧', 'droplet water'],
      ['🌊', 'wave ocean'],
      ['☀️', 'sun sunny'],
      ['⛅', 'partly cloudy'],
      ['☁️', 'cloud'],
      ['🌧️', 'rain'],
      ['⛈️', 'storm thunder'],
      ['🌈', 'rainbow'],
      ['❄️', 'snowflake cold'],
      ['🌍', 'earth globe world'],
    ],
  },
  {
    id: 'food',
    label: 'Food',
    icon: '🍽️',
    emoji: [
      ['🍎', 'apple'],
      ['🍌', 'banana'],
      ['🍇', 'grapes'],
      ['🍓', 'strawberry'],
      ['🥭', 'mango'],
      ['🍊', 'orange tangerine'],
      ['🍋', 'lemon'],
      ['🍉', 'watermelon'],
      ['🥥', 'coconut'],
      ['🥑', 'avocado'],
      ['🍅', 'tomato'],
      ['🥕', 'carrot'],
      ['🌽', 'corn'],
      ['🌶️', 'chilli pepper spicy'],
      ['🥔', 'potato'],
      ['🍞', 'bread'],
      ['🧀', 'cheese'],
      ['🥚', 'egg'],
      ['🍳', 'cooking fried egg'],
      ['🥞', 'pancakes'],
      ['🍕', 'pizza'],
      ['🍔', 'burger'],
      ['🌭', 'hot dog'],
      ['🌮', 'taco'],
      ['🍜', 'noodles ramen'],
      ['🍚', 'rice'],
      ['🍛', 'curry'],
      ['🥘', 'pan food'],
      ['🍲', 'stew pot'],
      ['🥟', 'dumpling momo'],
      ['🍱', 'bento'],
      ['🍣', 'sushi'],
      ['🍤', 'prawn fried'],
      ['🍦', 'ice cream'],
      ['🍰', 'cake slice'],
      ['🎂', 'birthday cake'],
      ['🍪', 'cookie biscuit'],
      ['🍫', 'chocolate'],
      ['🍬', 'sweet candy'],
      ['🍩', 'doughnut'],
      ['☕', 'coffee tea hot drink'],
      ['🍵', 'tea green'],
      ['🥤', 'cup straw soft drink'],
      ['🍺', 'beer'],
      ['🍻', 'cheers beers'],
      ['🥂', 'clink glasses celebrate'],
      ['🍷', 'wine'],
      ['🥛', 'milk'],
      ['💦', 'sweat droplets water'],
    ],
  },
  {
    id: 'work',
    label: 'Work',
    icon: '🧵',
    emoji: [
      ['🧵', 'thread sewing spool'],
      ['🧶', 'yarn knit wool'],
      ['🪡', 'sewing needle'],
      ['👕', 'tshirt shirt tee'],
      ['👖', 'jeans trousers denim'],
      ['👗', 'dress'],
      ['👔', 'shirt tie formal'],
      ['🧥', 'coat jacket'],
      ['🧣', 'scarf'],
      ['🧤', 'gloves'],
      ['🧦', 'socks'],
      ['👞', 'shoe'],
      ['👟', 'trainer sneaker'],
      ['👜', 'handbag'],
      ['🎒', 'backpack bag'],
      ['🪢', 'knot rope'],
      ['📦', 'package box parcel carton'],
      ['📮', 'postbox'],
      ['🚚', 'lorry delivery truck'],
      ['🚛', 'articulated lorry freight'],
      ['✈️', 'plane flight air'],
      ['🚢', 'ship sea freight'],
      ['🏭', 'factory plant'],
      ['🏢', 'office building'],
      ['🏬', 'store shop'],
      ['🔧', 'spanner wrench fix'],
      ['🔨', 'hammer'],
      ['🛠️', 'tools maintenance'],
      ['⚙️', 'gear settings machine'],
      ['🔩', 'nut bolt'],
      ['🧰', 'toolbox'],
      ['🧪', 'test tube sample'],
      ['🔬', 'microscope inspect qc'],
      ['📏', 'ruler measure'],
      ['📐', 'set square measure'],
      ['✂️', 'scissors cut cutting'],
      ['📋', 'clipboard checklist'],
      ['📝', 'memo note write'],
      ['📊', 'bar chart report'],
      ['📈', 'chart up growth'],
      ['📉', 'chart down loss'],
      ['🗓️', 'calendar date schedule'],
      ['⏰', 'alarm clock time'],
      ['⏳', 'hourglass waiting'],
      ['💰', 'money bag cash'],
      ['💵', 'banknote money'],
      ['💳', 'card payment'],
      ['🧾', 'receipt invoice bill'],
      ['🏷️', 'label tag price'],
      ['📌', 'pin'],
      ['📎', 'paperclip attach'],
      ['🔑', 'key access'],
      ['🔒', 'lock secure'],
      ['🔓', 'unlock open'],
      ['💡', 'idea lightbulb'],
      ['🔋', 'battery power'],
      ['🔌', 'plug power'],
      ['💻', 'laptop computer'],
      ['📱', 'phone mobile'],
      ['📞', 'telephone call'],
      ['📧', 'email mail'],
      ['🖨️', 'printer print'],
      ['📷', 'camera photo'],
      ['🎥', 'camera video film'],
      ['🔍', 'search magnify find'],
    ],
  },
  {
    id: 'activity',
    label: 'Activity',
    icon: '⚽',
    emoji: [
      ['⚽', 'football soccer'],
      ['🏀', 'basketball'],
      ['🏈', 'american football'],
      ['⚾', 'baseball'],
      ['🎾', 'tennis'],
      ['🏐', 'volleyball'],
      ['🏉', 'rugby'],
      ['🏸', 'badminton'],
      ['🏓', 'table tennis ping pong'],
      ['🏏', 'cricket'],
      ['🥅', 'goal net'],
      ['⛳', 'golf flag'],
      ['🎯', 'target bullseye goal'],
      ['🎳', 'bowling'],
      ['🎮', 'game controller'],
      ['🎲', 'dice'],
      ['🧩', 'puzzle piece'],
      ['♟️', 'chess pawn'],
      ['🎤', 'microphone sing'],
      ['🎧', 'headphones music'],
      ['🎵', 'music note'],
      ['🎸', 'guitar'],
      ['🥁', 'drum'],
      ['🎬', 'clapper film action'],
      ['🎨', 'art palette design'],
      ['🏆', 'trophy win award'],
      ['🥇', 'gold medal first'],
      ['🥈', 'silver medal second'],
      ['🥉', 'bronze medal third'],
      ['🏅', 'medal award'],
      ['🎉', 'party popper celebrate congrats'],
      ['🎊', 'confetti celebrate'],
      ['🎈', 'balloon'],
      ['🎁', 'gift present'],
      ['🚀', 'rocket launch fast ship'],
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '❤️',
    emoji: [
      ['❤️', 'red heart love'],
      ['🧡', 'orange heart'],
      ['💛', 'yellow heart'],
      ['💚', 'green heart'],
      ['💙', 'blue heart'],
      ['💜', 'purple heart'],
      ['🖤', 'black heart'],
      ['🤍', 'white heart'],
      ['💔', 'broken heart'],
      ['💕', 'two hearts'],
      ['💯', 'hundred perfect score'],
      ['✅', 'check tick done complete yes'],
      ['☑️', 'ballot check tick'],
      ['✔️', 'check mark tick'],
      ['❌', 'cross no wrong'],
      ['❎', 'cross mark button'],
      ['⭕', 'circle correct'],
      ['❗', 'exclamation important'],
      ['❓', 'question'],
      ['⚠️', 'warning caution'],
      ['🚫', 'prohibited banned no'],
      ['⛔', 'no entry stop'],
      ['🔴', 'red circle'],
      ['🟠', 'orange circle'],
      ['🟡', 'yellow circle'],
      ['🟢', 'green circle ok'],
      ['🔵', 'blue circle'],
      ['⚫', 'black circle'],
      ['⚪', 'white circle'],
      ['🟥', 'red square'],
      ['🟩', 'green square'],
      ['🔶', 'orange diamond'],
      ['🔷', 'blue diamond'],
      ['➕', 'plus add'],
      ['➖', 'minus subtract'],
      ['➗', 'divide'],
      ['✖️', 'multiply times'],
      ['🔺', 'up triangle increase'],
      ['🔻', 'down triangle decrease'],
      ['⬆️', 'up arrow'],
      ['⬇️', 'down arrow'],
      ['➡️', 'right arrow next'],
      ['⬅️', 'left arrow back'],
      ['🔄', 'refresh repeat cycle'],
      ['🔔', 'bell notification'],
      ['🔕', 'bell off mute'],
      ['💬', 'speech bubble comment'],
      ['💭', 'thought bubble'],
      ['🗨️', 'speech left'],
      ['👌', 'ok hand'],
      ['🆗', 'ok button'],
      ['🆕', 'new button'],
      ['🔝', 'top'],
      ['🈶', 'not free'],
      ['♻️', 'recycle'],
      ['⚖️', 'scales balance'],
      ['🕐', 'clock one'],
      ['🔗', 'link chain'],
      ['🏁', 'chequered flag finish'],
      ['🚩', 'triangular flag'],
      ['🇳🇵', 'nepal flag'],
      ['🇬🇧', 'united kingdom flag britain'],
    ],
  },
];

/** Flat search across every group, matched on the glyph's own words. */
export function searchEmoji(query: string): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const out: string[] = [];
  for (const group of EMOJI_GROUPS) {
    for (const [glyph, words] of group.emoji) {
      if (words.includes(q) && !out.includes(glyph)) out.push(glyph);
    }
  }
  return out;
}
